language: node_js
node_js:
  - "9"
  - "8"
  - "7"
services:
  - postgresql
env:
  - DATABASE_URL="postgres://postgres@localhost:5432/"
before_script:
  - psql -c 'create database travis;' -U postgres
